GPU: 3
b1: 0.5
b2: 0.999
batch_size: 1
datasets_folder: Robert
datasets_path: datasets
epoch: 0
gap_h: 64
gap_s: 150
gap_w: 64
img_h: 64
img_s: 320
img_w: 64
lr: 2.0e-05
n_epochs: 20
normalize_factor: 1
output_dir: ./results
train_datasets_size: 1000
